// Copyright (c) 2024-2026 Henry Wiechert (datafeta.io). SPDX-License-Identifier: AGPL-3.0-only
/**
 * Generates src/theme/tokens.generated.css from src/theme/tokens.def.json.
 *
 * Why a build step rather than authoring the CSS by hand: some consumers
 * cannot read CSS custom properties. Observable Plot's `maybeNumberChannel`
 * treats `var(...)` as a column name, `getContrastTextColor` needs a parseable
 * hex, and jsdom does not resolve `var()` at all — so those call sites must
 * import concrete values from TypeScript. One authored JSON feeding both
 * outputs is the only way those two views cannot drift.
 *
 * Runs from the `prestart` / `prebuild` hooks, next to generate-version.js.
 * The output is committed so a fresh clone and `npm test` work without it.
 */
const fs = require('fs');
const path = require('path');

const DEF_PATH = path.join(__dirname, '..', 'src', 'theme', 'tokens.def.json');
const OUT_PATH = path.join(__dirname, '..', 'src', 'theme', 'tokens.generated.css');
const DARK_SELECTOR = '[data-df-color-scheme="dark"]';

/** camelCase token name -> kebab-case custom property name. Mirrored in
 *  src/theme/tokens.ts; tokens.test.ts asserts the two agree. */
const cssVarName = (token) => `--df-${token.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`;

const definitions = JSON.parse(fs.readFileSync(DEF_PATH, 'utf8'));
const lightKeys = Object.keys(definitions.light);
const darkKeys = Object.keys(definitions.dark);

const missingInDark = lightKeys.filter((k) => !darkKeys.includes(k));
const missingInLight = darkKeys.filter((k) => !lightKeys.includes(k));
if (missingInDark.length || missingInLight.length) {
  console.error('tokens.def.json: light and dark must define the same tokens.');
  if (missingInDark.length) console.error('  missing from dark:', missingInDark.join(', '));
  if (missingInLight.length) console.error('  missing from light:', missingInLight.join(', '));
  process.exit(1);
}

const block = (selector, values) => [
  `${selector} {`,
  ...lightKeys.map((token) => `  ${cssVarName(token)}: ${values[token]};`),
  '}',
].join('\n');

const css = [
  '/*',
  ' * GENERATED by scripts/generate-tokens.js from tokens.def.json — do not edit.',
  ' *',
  ' * The dark block keys on the same attribute MUI\'s CssVarsProvider toggles',
  ' * (see src/theme/ThemeRoot.tsx), so one attribute flip switches this layer and',
  ' * --mui-palette-* together. See src/theme/THEMING.md.',
  ' */',
  '',
  block(':root', definitions.light),
  '',
  block(DARK_SELECTOR, definitions.dark),
  '',
].join('\n');

fs.writeFileSync(OUT_PATH, css);
console.log(`generate-tokens: wrote ${lightKeys.length} tokens x 2 schemes to ${path.relative(process.cwd(), OUT_PATH)}`);
