// Copyright (c) 2024-2026 Henry Wiechert (datafeta.io). SPDX-License-Identifier: AGPL-3.0-only
/**
 * Generates src/theme/tokens.generated.css from src/theme/tokens.def.json.
 *
 * Why a build step rather than authoring the CSS by hand: some consumers
 * cannot read CSS custom properties. Observable Plot's `maybeNumberChannel`
 * treats `var(...)` as a column name, `getContrastTextColor` needs a parseable
 * hex, and jsdom does not resolve `var()` at all — so those call sites must
 * import concrete values from TypeScript. One authored JSON feeding both
 * outputs is the only way those two views cannot drift.
 *
 * Runs from the `prestart` / `prebuild` hooks, next to generate-version.js.
 * The output is committed so a fresh clone and `npm test` work without it.
 */
const fs = require('fs');
const path = require('path');

const DEF_PATH = path.join(__dirname, '..', 'src', 'theme', 'tokens.def.json');
const OUT_PATH = path.join(__dirname, '..', 'src', 'theme', 'tokens.generated.css');

/**
 * `light` is the base scheme and lands in `:root`; every other scheme gets an
 * attribute block. The attribute value is the scheme's own key, which is also
 * what MUI's CssVarsProvider writes, so the two layers cannot disagree.
 */
const BASE_SCHEME = 'light';
const selectorFor = (scheme) => `[data-df-color-scheme="${scheme}"]`;

/** camelCase token name -> kebab-case custom property name. Mirrored in
 *  src/theme/tokens.ts; tokens.test.ts asserts the two agree. */
const cssVarName = (token) => `--df-${token.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`;

const definitions = JSON.parse(fs.readFileSync(DEF_PATH, 'utf8'));

const fail = (...lines) => {
  lines.forEach((line) => console.error(line));
  process.exit(1);
};

/**
 * A scheme is either a full table of values or a *patch* over another scheme:
 * `{ "extends": "dark", "values": { ... } }`. A variant that only lifts the
 * surfaces has no business restating the other ~140 tokens — the patch form
 * says what the variant *is*, and keeps a re-tune of the base from silently
 * skipping its variants.
 *
 * Mirrored in src/theme/tokens.def.ts; tokens.test.ts asserts the generated
 * CSS matches what that module resolves, which is what keeps the two honest.
 */
const isPatch = (def) => def !== null && typeof def === 'object' && 'extends' in def;

const resolve = (scheme, seen = []) => {
  const def = definitions[scheme];
  if (!def) fail(`tokens.def.json: scheme "${scheme}" is extended but not defined.`);
  if (!isPatch(def)) return def;

  if (seen.indexOf(scheme) !== -1) {
    fail(`tokens.def.json: circular extends (${seen.concat(scheme).join(' -> ')}).`);
  }
  const base = resolve(def.extends, seen.concat(scheme));
  const unknown = Object.keys(def.values).filter((k) => !(k in base));
  if (unknown.length) {
    // Without this a typo'd key would define a brand-new token for one scheme
    // only, which the parity check below reports as a missing token elsewhere
    // — a confusing way to hear about a misspelling.
    fail(
      `tokens.def.json: scheme "${scheme}" patches tokens that "${def.extends}" does not define:`,
      `  ${unknown.join(', ')}`,
    );
  }
  return Object.assign({}, base, def.values);
};

const schemes = Object.keys(definitions);
if (schemes[0] !== BASE_SCHEME) {
  fail(`tokens.def.json: "${BASE_SCHEME}" must be the first scheme, since it becomes :root.`);
}

const resolved = {};
schemes.forEach((scheme) => { resolved[scheme] = resolve(scheme); });

const baseKeys = Object.keys(resolved[BASE_SCHEME]);
schemes.forEach((scheme) => {
  if (scheme === BASE_SCHEME) return;
  const keys = Object.keys(resolved[scheme]);
  const missing = baseKeys.filter((k) => keys.indexOf(k) === -1);
  const extra = keys.filter((k) => baseKeys.indexOf(k) === -1);
  if (missing.length || extra.length) {
    fail(
      `tokens.def.json: every scheme must define the same tokens as "${BASE_SCHEME}".`,
      ...(missing.length ? [`  missing from ${scheme}: ${missing.join(', ')}`] : []),
      ...(extra.length ? [`  only in ${scheme}: ${extra.join(', ')}`] : []),
    );
  }
});

const block = (selector, values) => [
  `${selector} {`,
  ...baseKeys.map((token) => `  ${cssVarName(token)}: ${values[token]};`),
  '}',
].join('\n');

const css = [
  '/*',
  ' * GENERATED by scripts/generate-tokens.js from tokens.def.json — do not edit.',
  ' *',
  ' * The dark block keys on the same attribute MUI\'s CssVarsProvider toggles',
  ' * (see src/theme/ThemeRoot.tsx), so one attribute flip switches this layer and',
  ' * --mui-palette-* together. See src/theme/THEMING.md.',
  ' */',
  '',
  ...schemes.flatMap((scheme) => [
    block(scheme === BASE_SCHEME ? ':root' : selectorFor(scheme), resolved[scheme]),
    '',
  ]),
].join('\n');

fs.writeFileSync(OUT_PATH, css);
console.log(
  `generate-tokens: wrote ${baseKeys.length} tokens x ${schemes.length} schemes `
  + `(${schemes.join(', ')}) to ${path.relative(process.cwd(), OUT_PATH)}`,
);
